### ISSUE TITLE
Install Plugin on Calibre 2.20.0 Portable Fail

### ISSUE THREAD

**Issue by M1chae1** [fated/calibre_amazon_cn#2]
Error message

```
calibre, version 2.20.0
ERROR: Unhandled exception: <b>InvalidPlugin</b>:The plugin in u'/Users/Michael/Download/calibre_amazon_cn-master.zip' is invalid. It does not contain a top-level __init__.py file

calibre 2.20  isfrozen: True is64bit: True
Darwin-14.1.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '14.1.0', 'Darwin Kernel Version 14.1.0: Mon Dec 22 23:10:38 PST 2014; root:xnu-2782.10.72~2/RELEASE_X86_64')
Python 2.7.9
OSX: ('10.10.2', ('', '', ''), 'x86_64')
Traceback (most recent call last):
  File "site-packages/calibre/gui2/preferences/plugins.py", line 316, in add_plugin
  File "site-packages/calibre/customize/ui.py", line 388, in add_plugin
  File "site-packages/calibre/customize/ui.py", line 53, in load_plugin
  File "site-packages/calibre/customize/zipplugin.py", line 188, in load
  File "site-packages/calibre/customize/zipplugin.py", line 286, in _locate_code
InvalidPlugin: The plugin in u'/Users/Michael/Downloads/calibre_amazon_cn-master.zip' is invalid. It does not contain a top-level __init__.py file
```

**Comment by fated** [comment]
Hi, @M1chae1 
Since GitHub will automatically pack the source files under a folder like `calibre_amazon_cn-0.3.1` or `calibre_amazon_cn-master`, so directly import this zip file into calibre won't work.
Could you please unpack the zip file and get into the extracted folder and select all files and then repack that into a new zip file? This new zip file can be recognized by Calibre.

I've also uploaded a repacked zip file in the [release page](https://github.com/fated/calibre_amazon_cn/releases), please download `calibre_amazon_cn.zip` and import it to your Calibre, that should work.

Thanks for the feedback

**Comment by M1chae1** [comment]
The repacked file works. Thanks.

The Archive Utility on Mac will unzip the package under a folder that name is same as the zip filename even there is no folder on top-level. So I don't aware the folder created by github in the zip file.
